name: Java CI with Gradle

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    # trash by AI
    - name: Generate cache key
      id: cache-key
      run: |
        timestamp=$(date +%Y%m%d%H%M%S)
        echo "cache_key=buildcache-$timestamp" >> $GITHUB_OUTPUT
      
    - name: Restore cache
      uses: actions/cache@v4
      id: cache
      with:
        path: ./.gradle
        key: ${{ steps.cache-key.outputs.cache_key }}
        restore-keys: |
          buildcache-
  
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      with:
        gradle-version: '9.0.0'

    - name: Build with Gradle Wrapper
      run: gradle build
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        path: build/libs/*
